# Generated by Django 4.2 on 2024-02-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AISP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='uploadScore',
            field=models.FloatField(default=0.0),
        ),
    ]
